- name: hello world
  hosts: local
  connection: local # no need of username and password while connecting to local servers
  tasks:
  - name: print hello world
    ansible.builtin.debug:
      msg: "Hello World"
  