- name: play level variables
  hosts: local
  connection: local
  vars:
    COURSE: Ansible # this is equal to COURSE=Ansible in shell, in shell we refer as $VAR or ${VAR}
    DURATION: 10HR
    TRAINER: SivaKumar
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is {{ TRAINER }}"
      # VARS reference SHOULD BE IN DOUBLE QUOTES, THEN ONLY ANSIBLE UNDERSTANDS IT AS A VARIABLE.
  
  - name: print course information again
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is {{ TRAINER }}"