- name: variables from inventory
  hosts: local
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Hello, I am learning {{ COURSE }}, Duration: {{ DURATION }}, Trainer is: {{ TRAINER }}"