- name: understand vars preference
  hosts: local
  connection: local
  # vars:
  #   GREETING: "Hello from PLAY"
  # vars_files: 
  # - course.yaml
  # vars_prompt:
  # - name: GREETING
  #   prompt: Please enter the greeting
  #   private: false
  tasks:
  - name: print the greeting
    # vars:
    #   GREETING: "Hello from TASK"
    ansible.builtin.debug:
      msg: "{{ GREETING }}"

# command line variables output Preference order series:    After getting particular output comment out those script lines above 
# 1. command line or args
# 2. Task
# 3. File
# 4. Prompt
# 5. Play
# 6. Inventory
# [ No need to remember the order of preference ]