- name: ansible datatypes
  hosts: local
  connection: local
  vars:
    DURATION: 120 # this is number
    COURSE: "DevSecOps with AWS" # this is string
    IS_LIVE: true # boolean
    TOOLS: # List - referred by []
    - Linux
    - shell
    - Ansible
    CONCEPTS: # this is called map or dictionary or object. Object usually referred by { } braces and are in Key-Pairs.
      CI: Jenkins
      SCRIPTING: "Shell, Ansible, Terraform, Python"
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Course is: {{ COURSE }}, Duration: {{ DURATION }}, is live: {{ IS_LIVE }}, Tools are: {{ TOOLS }}, Concepts are: {{ CONCEPTS }}"