- name: functions
  hosts: local
  connection: local
  vars:
    persons: "Ramesh, Suresh, Tharun, Reddy" # string of variables
  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ person | default('Tharun') }}" # if we haven't defined a variable then we can give '| default (name)'

  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ persons | split(',') }}" # if we want to convert the string of variables into list, we use the delimitor 'split()' here.