- name: shell vs command
  hosts: frontend # remote server
  tasks:
  - name: redirect ls output to a file
    # ansible.builtin.command: "ls -ltr > /tmp/output.txt"
    ansible.builtin.shell: "ls -ltr > /tmp/output.txt"
